algoritmo "ex_32"
// Função : 32. Faça um programa que receba o peso de uma pessoa em quilos, calcule e mostre esse
///peso em gramas.
// Autor : Cristyan das Neves Silva
// Data : 20/05/2025
// Seção de Declarações 
var
pesoKg: real
inicio
// Seção de Comandos 
escreva("Informe seu peso em KG: ")
leia(pesoKg)
pesoKg <- pesoKg* 1000
escreva("Seu peso em gramas ficará: ", pesoKg," gramas")

fimalgoritmo
