algoritmo "ex_37"
// Função :     37. Faça um programa que calcule e mostre a tabuada de um número digitado pelo usuário.
// Autor : Cristyan das Neves Silva
// Data : 20/05/2025
// Seção de Declarações 
var
tabuada, num, resultado: inteiro
inicio
// Seção de Comandos 
escreva("Informe um numero para ver sua tabuada: ")
leia(num)
para tabuada de 1 ate 10 faca
     resultado <- num * tabuada
     escreval(num," x",tabuada,"=", resultado)
fimpara
fimalgoritmo
